### ISSUE TITLE
#15b0c5 color sets icon color to black instead of white

### ISSUE THREAD

**Issue by andreicristianpetcu** [taboca/browser-adaptation-dynamic-theme#20]
Hi,

I have this web site that https://app.glassfrog.com/ has white icons and text in the toolbar yet Chameleon Dynamic Theme sets it to dark and it looks strange.

![screenshot from 2018-08-10 14-44-18](https://user-images.githubusercontent.com/922368/43956516-39ce3160-9cad-11e8-9f73-08bafaeba324.png)

Please make it so that it sets the text color to white.

**Comment by taboca** [comment]
New fix from https://github.com/taboca/browser-adaptation-dynamic-theme/pull/18 helped with this

**Comment by taboca** [comment]
Please test with version 2.0.
